=== stackmuncher/stm/stackmuncher_lib/stm_rules/schemas/muncher.json
{
  "$id": "https://schemas.stackmuncher.com/muncher.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "muncher",
  "description": "Describes an analyser for a particular file type for a particular language. E.g. .cs or .csproj - same language, different structure.",
  "type": "object",
  "required": [
    "language",
    "$schema",
    "line_endings"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "description": "URL of the JSON schema. Specific to VSCode."
    },
    "line_endings": {
      "const": "unix",
      "description": "Only LF line endings are allowed for consistency."
    },
    "language": {
      "type": "string",
      "description": "Computer language name for humans, e.g. Rust."
    },
    "keywords": {
      "type": "array",
      "description": "List of Regex for keywords.",
      "minItems": 1,
      "uniqueItems": true
    },
    "bracket_only": {
      "type": "array",
      "description": "List of Regex for lines with block brackets, e.g. {}.",
      "minItems": 1,
      "uniqueItems": true
    },
    "line_comments": {
      "type": "array",
      "description": "List of Regex for full line comments.",
      "minItems": 1,
      "uniqueItems": true
    },
    "inline_comments": {
      "type": "array",
      "description": "List of Regex for inline comments.",
      "minItems": 1,
      "uniqueItems": true
    },
    "doc_comments": {
      "type": "array",
      "description": "List of Regex for documentation comments.",
      "minItems": 1,
      "uniqueItems": true
    },
    "block_comments_start": {
      "type": "array",
      "description": "List of Regex for starting a block comment.",
      "minItems": 1,
      "uniqueItems": true
    },
    "block_comments_end": {
      "type": "array",
      "description": "List of Regex for ending a block comment."
    },
    "refs": {
      "type": "array",
      "description": "List of Regex for `use` or `include` references. Can refer to the package, namespace or inner members.",
      "minItems": 1,
      "uniqueItems": true
    },
    "packages": {
      "type": "array",
      "description": "List of Regex for package references for the package manger. Only refer to the package, not inner members.",
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "additionalProperties": false
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/ruby.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "Ruby",
  "bracket_only": [
    "^\\s*[{}\\[\\]][\\s;,]*$"
  ],
  "line_comments": [
    "^[[:blank:]]*#.{5,}"
  ],
  "inline_comments": [
    "[.[^#\\s]]+[[:blank:]]+#.{5,}"
  ],
  "doc_comments": [
    "^[[:blank:]]*#[[:blank:]]*@[a-zA-Z]+.{5,}"
  ],
  "refs": [
    "^[[:blank:]]*require[[:blank:]]+'([a-zA-Z0-9-_.]+)'"
  ],
  "packages": [
    "(?i).add_runtime_dependency\\s+['\"]([a-zA-Z0-9-_\\.]+)['\"]",
    "(?i).add_development_dependency\\s+['\"]([a-zA-Z0-9-_\\.]+)['\"]"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/css.json
{
  "$schema": "https://raw.githubusercontent.com/rimutaka/stm/master/assets/schemas/muncher.json",
  "line_endings": "unix",
  "language": "CSS",
  "bracket_only": [
    "^\\s*[{}\\[\\]][\\s]*$"
  ],
  "block_comments_start": [
    "(?i)^\\s*/\\*"
  ],
  "block_comments_end": [
    "(?i)\\*/\\s*$"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/cpp.cpp.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "C++",
  "bracket_only": [
    "^[[:blank:]]*[{}\\[\\]\\(\\)][[:blank:];,)]*$",
    "^[[:blank:]]*//[[:blank:]]*.{0,5}$"
  ],
  "line_comments": [
    "^[[:blank:]]*//[:blank:]*.{5,}"
  ],
  "inline_comments": [
    "[^[:space:]]+[[:blank:]]*//.{5,}"
  ],
  "block_comments_start": [
    "^[[:blank:]]*/\\*"
  ],
  "block_comments_end": [
    "\\*/[[:blank:]]*$"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/html.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "HTML",
  "bracket_only": [
    "^[[[:blank:]]%{/]*[{}\\[\\]\\(\\)<>][[:blank:];,%})]*$"
  ],
  "block_comments_start": [
    "^[[:blank:]]*<!--",
    "^[[:blank:]]*/\\*"
  ],
  "block_comments_end": [
    "-->",
    "\\*/[[:blank:]]*$"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/ruby.erb.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "eRuby",
  "bracket_only": [
    "^[[:blank:]]*<%[[:blank:]]*$",
    "^[[:blank:]]*-?%>[[:blank:]]*$"
  ],
  "line_comments": [
    "^[[:blank:]]*-#.{5,}"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/csharp.cs.json
{
  "$schema": "https://raw.githubusercontent.com/rimutaka/stm/master/assets/schemas/muncher.json",
  "line_endings": "unix",
  "language": "C#",
  "keywords": [
    "\\babstract\\b",
    "\\badd\\b",
    "\\balias\\b",
    "\\bas\\b",
    "\\bascending\\b",
    "\\basync\\b",
    "\\bawait\\b",
    "\\bbase\\b",
    "\\bbool\\b",
    "\\bbreak\\b",
    "\\bby\\b",
    "\\bbyte\\b",
    "\\bcase\\b",
    "\\bcatch\\b",
    "\\bchar\\b",
    "\\bchecked\\b",
    "\\bclass\\b",
    "\\bconst\\b",
    "\\bcontinue\\b",
    "\\bdecimal\\b",
    "\\bdefault\\b",
    "\\bdelegate\\b",
    "\\bdescending\\b",
    "\\bdo\\b",
    "\\bdouble\\b",
    "\\bdynamic\\b",
    "\\belse\\b",
    "\\benum\\b",
    "\\bequals\\b",
    "\\bevent\\b",
    "\\bexplicit\\b",
    "\\bextern\\b",
    "\\bfalse\\b",
    "\\bfinally\\b",
    "\\bfixed\\b",
    "\\bfloat\\b",
    "\\bfor\\b",
    "\\bforeach\\b",
    "\\bfrom\\b",
    "\\bget\\b",
    "\\bglobal\\b",
    "\\bgoto\\b",
    "\\bgroup\\b",
    "\\bif\\b",
    "\\bimplicit\\b",
    "\\bin\\b",
    "\\bint\\b",
    "\\binterface\\b",
    "\\binternal\\b",
    "\\binto\\b",
    "\\bis\\b",
    "\\bjoin\\b",
    "\\blet\\b",
    "\\block\\b",
    "\\blong\\b",
    "\\bnameof\\b",
    "\\bnamespace\\b",
    "\\bnew\\b",
    "\\bnull\\b",
    "\\bobject\\b",
    "\\bon\\b",
    "\\boperator\\b",
    "\\borderby\\b",
    "\\bout\\b",
    "\\boverride\\b",
    "\\bparams\\b",
    "\\bpartial (method)\\b",
    "\\bpartial (type)\\b",
    "\\bprivate\\b",
    "\\bprotected\\b",
    "\\bpublic\\b",
    "\\breadonly\\b",
    "\\bref\\b",
    "\\bremove\\b",
    "\\breturn\\b",
    "\\bsbyte\\b",
    "\\bsealed\\b",
    "\\bselect\\b",
    "\\bset\\b",
    "\\bshort\\b",
    "\\bsizeof\\b",
    "\\bstackalloc\\b",
    "\\bstatic\\b",
    "\\bstring\\b",
    "\\bstruct\\b",
    "\\bswitch\\b",
    "\\bthis\\b",
    "\\bthrow\\b",
    "\\btrue\\b",
    "\\btry\\b",
    "\\btypeof\\b",
    "\\buint\\b",
    "\\bulong\\b",
    "\\bunchecked\\b",
    "\\bunmanaged\\b",
    "\\bunsafe\\b",
    "\\bushort\\b",
    "\\busing\\b",
    "\\bvalue\\b",
    "\\bvar\\b",
    "\\bvirtual\\b",
    "\\bvoid\\b",
    "\\bvolatile\\b",
    "\\bwhen\\b",
    "\\bwhere\\b",
    "\\bwhile\\b",
    "\\byield\\b"
  ],
  "bracket_only": [
    "^\\s*[{}\\[\\]][\\s;,]*$"
  ],
  "line_comments": [
    "^\\s*//\\s*.{10,}"
  ],
  "inline_comments": [
    "^[.[^/\n]]+\\s//\\s.{10,}"
  ],
  "doc_comments": [
    "^\\s+///\\s+.{8,}"
  ],
  "block_comments_start": [
    "(?i)^\\s*/\\*"
  ],
  "block_comments_end": [
    "(?i)\\*/\\s*$"
  ],
  "refs": [
    "^\\s*using\\s+([A-Za-z0-9_\\.]+);"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/terraform.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "Terraform",
  "line_comments": [
    "^[[:blank:]]*#.{5,}"
  ],
  "inline_comments": [
    "[.[^#[[:blank:]]]]+[[:blank:]]+#.{5,}"
  ],
  "bracket_only": [
    "^[[:blank:]]*[{}\\[\\]\\(\\)][[:blank:]]*$",
    "^[[:blank:]]*#[[:blank:]]*.{0,5}$"
  ],
  "packages": [
    "^[[:blank:]]*source[[:blank:]]*=[[:blank:]]*\"[[:alnum:]][[[:alnum:]]-_]+/([[[:alnum:]]-_]+(?:/[[[:alnum:]]-_]+)*)\""
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/cicd.github.yml.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "GitHubCICD",
  "line_comments": [
    "^[[:blank:]]*#.{5,}"
  ],
  "inline_comments": [
    "[.[^#\\s]]+[[:blank:]]+#.{5,}"
  ],
  "bracket_only": [
    "^[[:blank:]]*[{}\\[\\]\\(\\)][[:blank:];,)]*$",
    "^[[:blank:]]*#[[:blank:]]*.{0,5}$"
  ]
}
