=== stackmuncher/stm/stackmuncher_lib/stm_rules/schemas/muncher.json
{
  "$id": "https://schemas.stackmuncher.com/muncher.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "muncher",
  "description": "Describes an analyser for a particular file type for a particular language. E.g. .cs or .csproj - same language, different structure.",
  "type": "object",
  "required": [
    "language",
    "$schema",
    "line_endings"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "description": "URL of the JSON schema. Specific to VSCode."
    },
    "line_endings": {
      "const": "unix",
      "description": "Only LF line endings are allowed for consistency."
    },
    "language": {
      "type": "string",
      "description": "Computer language name for humans, e.g. Rust."
    },
    "keywords": {
      "type": "array",
      "description": "List of Regex for keywords.",
      "minItems": 1,
      "uniqueItems": true
    },
    "bracket_only": {
      "type": "array",
      "description": "List of Regex for lines with block brackets, e.g. {}.",
      "minItems": 1,
      "uniqueItems": true
    },
    "line_comments": {
      "type": "array",
      "description": "List of Regex for full line comments.",
      "minItems": 1,
      "uniqueItems": true
    },
    "inline_comments": {
      "type": "array",
      "description": "List of Regex for inline comments.",
      "minItems": 1,
      "uniqueItems": true
    },
    "doc_comments": {
      "type": "array",
      "description": "List of Regex for documentation comments.",
      "minItems": 1,
      "uniqueItems": true
    },
    "block_comments_start": {
      "type": "array",
      "description": "List of Regex for starting a block comment.",
      "minItems": 1,
      "uniqueItems": true
    },
    "block_comments_end": {
      "type": "array",
      "description": "List of Regex for ending a block comment."
    },
    "refs": {
      "type": "array",
      "description": "List of Regex for `use` or `include` references. Can refer to the package, namespace or inner members.",
      "minItems": 1,
      "uniqueItems": true
    },
    "packages": {
      "type": "array",
      "description": "List of Regex for package references for the package manger. Only refer to the package, not inner members.",
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "additionalProperties": false
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/sql.json
{
  "$schema": "https://raw.githubusercontent.com/rimutaka/stm/master/assets/schemas/muncher.json",
  "line_endings": "unix",
  "language": "SQL",
  "line_comments": [
    "^\\s*--\\s*.{10,}"
  ],
  "inline_comments": [
    "^.+--.{10,}$"
  ],
  "block_comments_start": [
    "(?i)^\\s*/\\*"
  ],
  "block_comments_end": [
    "(?i)\\*/\\s*$"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/go.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "Go",
  "bracket_only": [
    "^[[:blank:]]*[{}\\[\\]\\(\\)][\\s;,)]*$",
    "^[[:blank:]]*//[[:blank:]]*.{0,5}$"
  ],
  "line_comments": [
    "^\\s*//\\s*.{5,}"
  ],
  "inline_comments": [
    "^[.[^/\n]]+\\s//\\s.{10,}"
  ],
  "block_comments_start": [
    "(?i)^\\s*/\\*"
  ],
  "block_comments_end": [
    "(?i)\\*/\\s*$"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/jupyter.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "Jupyter",
  "bracket_only": [
    "^[[:blank:]]*[{}\\[\\]\\(\\)][[:blank:];,)]*$"
  ],
  "refs": [
    "^\\s*\"\\s*import\\s+([A-Za-z0-9_\\.]+)",
    "^\\s*\"\\s*from\\s+([A-Za-z0-9_\\.]+)\\s+import\\s+([A-Za-z0-9_\\.]+)"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/python.py.json
{
  "$schema": "https://raw.githubusercontent.com/rimutaka/stm/master/assets/schemas/muncher.json",
  "line_endings": "unix",
  "language": "Python",
  "line_comments": [
    "^\\s*#\\s*.{10,}"
  ],
  "refs": [
    "^\\s*import\\s+([A-Za-z0-9_\\.]+)",
    "^\\s*from\\s+([A-Za-z0-9_\\.]+)\\s+import\\s+([A-Za-z0-9_\\.]+)"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/powershell.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "PowerShell",
  "bracket_only": [
    "^\\s*[{}\\[\\]][\\s;,]*$"
  ],
  "line_comments": [
    "^\\s*#.{10,}"
  ],
  "inline_comments": [
    "^.+\\s+#.{5,}"
  ],
  "block_comments_start": [
    "^\\s*<#"
  ],
  "block_comments_end": [
    "^.*#>"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/js.json
{
  "$schema": "https://raw.githubusercontent.com/stackmuncher/stm_app/master/stackmuncher_lib/stm_rules/schemas/muncher.json",
  "line_endings": "unix",
  "language": "JavaScript",
  "bracket_only": [
    "^\\s*[{}\\[\\]][\\s;,)]*$"
  ],
  "line_comments": [
    "^\\s*//\\s*.{10,}"
  ],
  "inline_comments": [
    "^[.[^/\n]]+\\s//\\s.{10,}"
  ],
  "block_comments_start": [
    "(?i)^\\s*/\\*"
  ],
  "block_comments_end": [
    "(?i)\\*/\\s*$"
  ]
}

=== stackmuncher/stm/stackmuncher_lib/stm_rules/munchers/rust.rs.json
{
  "$schema": "https://raw.githubusercontent.com/rimutaka/stm/master/assets/schemas/muncher.json",
  "line_endings": "unix",
  "language": "Rust",
  "keywords": [
    "\\bas\\b",
    "\\bbreak\\b",
    "\\bconst\\b",
    "\\bcontinue\\b",
    "\\bcrate\\b",
    "\\belse\\b",
    "\\benum\\b",
    "\\bextern\\b",
    "\\bfalse\\b",
    "\\bfn\\b",
    "\\bfor\\b",
    "\\bif\\b",
    "\\bimpl\\b",
    "\\bin\\b",
    "\\blet\\b",
    "\\bloop\\b",
    "\\bmatch\\b",
    "\\bmod\\b",
    "\\bmove\\b",
    "\\bmut\\b",
    "\\bpub\\b",
    "\\bref\\b",
    "\\breturn\\b",
    "\\bself\\b",
    "\\bSelf\\b",
    "\\bstatic\\b",
    "\\bstruct\\b",
    "\\bsuper\\b",
    "\\btrait\\b",
    "\\btrue\\b",
    "\\btype\\b",
    "\\bunsafe\\b",
    "\\buse\\b",
    "\\bwhere\\b",
    "\\bwhile\\b",
    "\\basync\\b",
    "\\bawait\\b",
    "\\bdyn\\b",
    "\\byield\\b",
    "\\btry\\b",
    "\\bunion\\b"
  ],
  "bracket_only": [
    "^\\s*[{}\\[\\]][\\s;,]*$"
  ],
  "line_comments": [
    "^\\s*//\\s*.{10,}"
  ],
  "inline_comments": [
    "^[.[^/\n]]+\\s//\\s.{10,}"
  ],
  "doc_comments": [
    "^\\s*///\\s*.{8,}",
    "^//!\\s*.{8,}"
  ],
  "block_comments_start": [
    "(?i)^\\s*/\\*"
  ],
  "block_comments_end": [
    "(?i)\\*/\\s*$"
  ]
}
